language: node_js
node_js: 6 7
git:
  depth: 3
cache: yarn
env:
  global:
  - secure: VoVxKFO4m6xmhcCV4hnZgvJuNdEsfBC5ys0eGxilaC6INhNBrfMKGAWo4Nic41H/0vhiPdvvm4jl4PgTjh4hOa9YVRInndwG59cGixzuQx97Hw6CnPwBt7Ls9rev/ToiuUSHP2JG9/LodtuwROHMK4Dn6x4xGf9wWRO59YhpJPbMnz00qbS7kb+FoFwE/OUaCA6MovrmFbDSpBFqgCf2pJcVHNSjg+BNMlp+RDvvloh9ekYucivV/t9l2x+wxB7T15ttPM3dD7w+cVmPNNHsKzzjXsWhTT/CKjj/GZoD59AcjB7prAfhsR2+a0hJkV3eww5QzBVTMhkHqt9fu4ipiG1bnZMbznooa7UGE495KezxkkiQGD3BafDxOJ2t0JpeSIKqpaAfmRyTOi/Ntlhk6Ga/kwRA0sPejPFxRY5jY8yh0/WuKt9PoIzSDyoR+j5RIHf4c4IWqrBgNzmW/bB1keduT/g+1O5bOAjIHZPL/Qrslot6yGVDbAP9fbHrFM1jq/xQYejePsRZOxR2pX3w+bOE55N5rTMuOtU4pRdDuhA6HOLQBscDZkN1P8ganxVNlAnVcU1Uz2nFthy+ANCI0XiC/AUUg69RZKsGF0I/LbgpooPu7e5q97lXauQeu8yNor3jvq9FETeHb7si3t53+mQtqYvssN2DuG1b7G1Vk4k=
  - secure: CILZYK0V5rblgL+b4eTguvu+uxvME+FiU685LQrbqU8EPFCImLdA9TYmCe690LrRdC6/XUrigIB2BytRHMYlhDJia2voq1fWktiVkfPQF2AxgE2jvef3QWDRTjFV6SCneP4KacxyupxiN+QdwVjH0LUP89MLuUPVovxQqRZsnwLb80vc3xjejhOAltZUrbZYiohzJmPDzIAn8wHerErWX/P9BfCdTWtfH0r5pusrhUz9f3M8TEW5T1smtATA7hVSZFS8cP7MxCjChbpWxP4wzcW3Jn3G8ONJCIFPhob8jyu+4hvoHS0KvOcFm0fb/tHxBggsAd0hFsQWTSaxZmXQsU0ID2aMv2LUQ/jBIulsP0rQWaQhwhSvaLc5+R2blOb4ujLy0YRgmRrY/PGLRN07peNswhmiMH6DrpYGowwi//+2PoeuHIlTAkb+8njxfH5yKT3tV1S+kHUf0zv99et/N57BlmHbzt8PEaeErY1P8H0rJqK/QPkPCo7XZTuxQu8aHaNWu1BJuil5GhwQphT8CKncsUO8q7kTOvgo3BgOJKJp/lJZRChB0hV5R0VbnieKlXwh5hmNRktbLpLwkVOP7Xeg/JJJ3TmBC+ciHnQbitPsKECJen25f4tkiTFDEo0U2xSZqF2KVIzCEbUKHf3VTEfKJojaPEQeMdGOzdQJHkY=
before_install:
- openssl aes-256-cbc -K $encrypted_87d951632a63_key -iv $encrypted_87d951632a63_iv
  -in .travis/rudy-site-deploy.enc -out rudy-site-deploy -d
- git config --global user.email "$GH_USER_EMAIL"
- git config --global user.name "$GH_USER_NAME"
- git config --global user.name
- echo "$GH_USER_NAME"
script: yarn test
after_script: yarn build
